name: Upload workflow documentation
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  workflow_call:
    inputs:
      upload_path:
        required: true
        type: string
    secrets:
      gcp_credentials:
        required: true

jobs:
  upload:
    name: Upload Documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workflows    

    steps:

    - uses: actions/checkout@master

    - name: Auth gcloud 
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.gcp_credentials }}
        project_id: tundra-central

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v0
    
    - run: echo "uploading to ${{ inputs.upload_path }}"

    - run: gsutil cp citations.md ${{ inputs.upload_path }}/citations.md
    - run: |
        for d in */; do 
          gsutil cp "${d}overview.md" "${{ inputs.upload_path }}/${d}overview.md"
          gsutil cp "${d}README.md" "${{ inputs.upload_path }}/${d}readme.md"
          gsutil cp "${d}inputs.md" "${{ inputs.upload_path }}/${d}inputs.md"
          gsutil cp "${d}outputs.md" "${{ inputs.upload_path }}/${d}outputs.md"
        done
